[package]
name = "typstify"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description.workspace = true

[lib]
name = "typstify"
path = "src/lib.rs"

[[bin]]
name = "typstify"
path = "src/main.rs"

[dependencies]
typstify-core.workspace = true
typstify-generator.workspace = true
typstify-parser.workspace = true

axum.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
notify.workspace = true
open.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
tower-http = { workspace = true, features = ["fs", "cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
walkdir = { workspace = true }
